### ISSUE TITLE
AllChunkInfo is not defined

### ISSUE THREAD

**Issue by heresergio** [comerford/mongodb-scripts#3]
Hi! I think, that you should to change startup instruction in comment line '//AllChunkInfo("database.collection", true);' cause I had error "AllChunkInfo is not defined"
I need to execute 'sh.printAllChunkInfo("database.collection", true);', because it's real function's name :)

**Comment by comerford** [comment]
I am going to guess that is because this has been removed from MongoDB in a subsequent release. The code here was written for version 2.6 if I remember correctly. Things have changed *a lot* since then, and massively in terms of how sharding works. Unfortunately I have not updated my own knowledge of MongoDB in 5+ years, so I don't think I will be updating this code any time soon.
